import type { Meta, StoryObj } from "@storybook/react";
import { KpButton, VARIANT, ButtonColor } from "./KpButton";
import { ICONS, IconType } from "../kpIcons/KpIcon";

// More on how to set up stories at: https://storybook.js.org/docs/react/writing-stories/introduction
const meta = {
  title: "Example/KpButton",
  component: KpButton,
  argTypes: {
    variant: {
      options: [
        VARIANT.PRIMARY,
        VARIANT.SECONDARY,
        VARIANT.TERTIARY,
        VARIANT.TEXT,
      ],
      control: { type: "radio" },
    },
    size: {
      options: ["default", "small"],
      control: { type: "radio" },
    },
    buttonColor: {
      options: [ButtonColor.PRIMARY, ButtonColor.SECONDARY],
      control: { type: "radio" },
    },
    leftIcon: {
      options: [
        ICONS.GROUPOUTLINE,
        ICONS.ADDACCOUNT,
        ICONS.LOCKACCOUNT,
        ICONS.ADD,
        ICONS.ARROWBACK,
        ICONS.ARROWBACKIOS,
        ICONS.CREATEICON,
        ICONS.DELETE,
        ICONS.ATOM,
        ICONS.ARROWFORWARD,
        ICONS.ARROWFORWARDIOS,
        ICONS.ERROR,
        ICONS.ERROROUTLINE,
        ICONS.BELLHORNICON,
        ICONS.INVENTORY,
        ICONS.INVENTORYOUTLINE,
        ICONS.NOTIFICATIONOUTLINE,
        ICONS.REPORTGMAILERROR,
        ICONS.WARNINGAMBER,
        ICONS.INVENTORY,
        ICONS.INVENTORYOUTLINE,
        ICONS.INVITATION,
        ICONS.CANCELICON,
        ICONS.CHECK,
        ICONS.CHECKOUTLINE,
        ICONS.CHECKCIRCLE,
        ICONS.DOUBLEARROWLEFT,
        ICONS.DOUBLEARROWRIGHT,
        ICONS.ARROWDOWN,
        ICONS.ARROWTOP,
        ICONS.ARROWLEFT,
        ICONS.ARROWRIGHT,
        ICONS.ARROWUP,
        ICONS.CIRCLE,
        ICONS.CLOCK,
        ICONS.CANCEL,
        ICONS.CANCELOUTLINE,
        ICONS.SETTINGSICON,
        ICONS.CREDITCARD,
        ICONS.DOTSHORIZOUTLINE,
        ICONS.DOTSVERTLINE,
        ICONS.DOWNLOADICON,
        ICONS.EMOCONFUSED,
        ICONS.EMOCRY,
        ICONS.EMOEXCITED,
        ICONS.EMOSATISFIED,
        ICONS.EMONEUTRAL,
        ICONS.VISIBILITY,
        ICONS.FILTEROUTLINE,
        ICONS.FINANCEOUTLINE,
        ICONS.GIFTCARD,
        ICONS.HANDSHAKE,
        ICONS.HELPCERCLE,
        ICONS.INFOOUTLINE,
        ICONS.SEARCHIOCN,
        ICONS.MENUOUTLINE,
        ICONS.REMOVEICON,
        ICONS.SHIELDACCOUNT,
        ICONS.STARICON,
        ICONS.STARICONPLUS,
        ICONS.TEXTBOXEDIT,
        ICONS.THUMBDOWN,
        ICONS.THUMBUP,
        ICONS.TRASHICON,
        ICONS.UNFOLDMORE,
        ICONS.UPLOADICON,
        ICONS.WINDOWCLOSE,
        ICONS.RELOADICON,
        ICONS.UNFOLDLESSICON,
      ],
      control: { type: "select" },
    },
    rightIcon: {
      options: [
        ICONS.GROUPOUTLINE,
        ICONS.ADDACCOUNT,
        ICONS.LOCKACCOUNT,
        ICONS.ADD,
        ICONS.ARROWBACK,
        ICONS.ARROWBACKIOS,
        ICONS.CREATEICON,
        ICONS.DELETE,
        ICONS.ATOM,
        ICONS.ARROWFORWARD,
        ICONS.ARROWFORWARDIOS,
        ICONS.ERROR,
        ICONS.ERROROUTLINE,
        ICONS.BELLHORNICON,
        ICONS.INVENTORY,
        ICONS.INVENTORYOUTLINE,
        ICONS.NOTIFICATIONOUTLINE,
        ICONS.REPORTGMAILERROR,
        ICONS.WARNINGAMBER,
        ICONS.INVENTORY,
        ICONS.INVENTORYOUTLINE,
        ICONS.INVITATION,
        ICONS.CANCELICON,
        ICONS.CHECK,
        ICONS.CHECKOUTLINE,
        ICONS.CHECKCIRCLE,
        ICONS.DOUBLEARROWLEFT,
        ICONS.DOUBLEARROWRIGHT,
        ICONS.ARROWDOWN,
        ICONS.ARROWTOP,
        ICONS.ARROWLEFT,
        ICONS.ARROWRIGHT,
        ICONS.ARROWUP,
        ICONS.CIRCLE,
        ICONS.CLOCK,
        ICONS.CANCEL,
        ICONS.CANCELOUTLINE,
        ICONS.SETTINGSICON,
        ICONS.CREDITCARD,
        ICONS.DOTSHORIZOUTLINE,
        ICONS.DOTSVERTLINE,
        ICONS.DOWNLOADICON,
        ICONS.EMOCONFUSED,
        ICONS.EMOCRY,
        ICONS.EMOEXCITED,
        ICONS.EMOSATISFIED,
        ICONS.EMONEUTRAL,
        ICONS.VISIBILITY,
        ICONS.FILTEROUTLINE,
        ICONS.FINANCEOUTLINE,
        ICONS.GIFTCARD,
        ICONS.HANDSHAKE,
        ICONS.HELPCERCLE,
        ICONS.INFOOUTLINE,
        ICONS.SEARCHIOCN,
        ICONS.MENUOUTLINE,
        ICONS.REMOVEICON,
        ICONS.SHIELDACCOUNT,
        ICONS.STARICON,
        ICONS.STARICONPLUS,
        ICONS.TEXTBOXEDIT,
        ICONS.THUMBDOWN,
        ICONS.THUMBUP,
        ICONS.TRASHICON,
        ICONS.UNFOLDMORE,
        ICONS.UPLOADICON,
        ICONS.WINDOWCLOSE,
        ICONS.RELOADICON,
        ICONS.UNFOLDLESSICON,
      ],
      control: { type: "select" },
    },
  },
  tags: ["autodocs"],
} satisfies Meta<typeof KpButton>;

export default meta;
type Story = StoryObj<typeof meta>;

// More on writing stories with args: https://storybook.js.org/docs/react/writing-stories/args
export const Basic_Button: Story = {
  args: {
    variant: VARIANT.PRIMARY,
    label: "Button",
    disabled: false,
    size: "default",
    buttonColor: ButtonColor.PRIMARY,
    customStyle: {},
    hasLeftIcon: false,
    leftIconType: IconType.MUI,
    leftIcon: ICONS.CREATEICON,
    leftIconSize: 0.9,
    hasRightIcon: false,
    rightIconType: IconType.MUI,
    rightIcon: ICONS.ARROWFORWARDIOS,
    rightIconSize: 0.9,
    iconColor: "#fff",
  },
};