import type {Meta, StoryObj} from '@storybook/react';

import {KpModal, ModalTestJSXElementTwo, MODALTYPE, ModalButtonColor, MODALVARIANT, ModalTestJSXElementOne, ModelTestFooterElement, ModelTestHeaderElement} from './KpModal';
import {ICONS} from "../kpIcons/KpIcon";

// More on how to set up stories at: https://storybook.js.org/docs/react/writing-stories/introduction
const meta = {
    title: 'Example/KpModal',
    component: KpModal,
    tags: ['autodocs'],
} satisfies Meta<typeof KpModal>;

export default meta;
type Story = StoryObj<typeof meta>;

// More on writing stories with args: https://storybook.js.org/docs/react/writing-stories/args


export const Basic_Modal: Story = {
    args: {
        type: MODALTYPE.DEFAULT,
        title: 'Title',
        content: ModalTestJSXElementOne(),
        submitBtnVariant: MODALVARIANT.PRIMARY,
        submitBtnSize: 'default',
        submitBtnColor: ModalButtonColor.PRIMARY,
        submitBtnText: 'Submit',
        cancelBtnText: 'Cancel',
        isOpen: true,
        submitBtnHasLeftIcon: false,
        submitBtnLeftIcon: ICONS.ARROWFORWARDIOS,
        submitBtnHasRightIcon: false,
        submitBtnRightIcon: ICONS.ADDACCOUNT,
        submitBtnDisabled: false,
        cancelBtnVariant: MODALVARIANT.PRIMARY,
        cancelBtnSize: 'default',
        cancelBtnColor: ModalButtonColor.PRIMARY,
        cancelBtnHasLeftIcon: false,
        cancelBtnLeftIcon: ICONS.ARROWDOWN,
        cancelBtnHasRightIcon: false,
        cancelBtnRightIcon: ICONS.ARROWLEFT,
        cancelBtnDisabled: false,
        isFooterContent: true,
        footerContent: ModelTestFooterElement(),
        isHeaderContent: true,
        headerContent: ModelTestHeaderElement(),
    },
    argTypes: {
        type: {
            options: [MODALTYPE.DEFAULT, MODALTYPE.INFORMATIVE],
            control: {type: "radio"}
        },
        submitBtnVariant: {
            options: [MODALVARIANT.PRIMARY, MODALVARIANT.SECONDARY, MODALVARIANT.TERTIARY, MODALVARIANT.TEXT],
            control: {type: 'radio'},
        },
        submitBtnSize: {
            options: ['default', 'small'],
            control: {type: 'radio'}
        },
        submitBtnColor: {
            options: [ModalButtonColor.PRIMARY, ModalButtonColor.SECONDARY],
            control: {type: 'radio'}
        },
        submitBtnHasLeftIcon: {
            options: [true, false],
            control: {type: "radio"}
        },
        submitBtnLeftIcon: {
            options: [
                ICONS.GROUPOUTLINE,
                ICONS.ADDACCOUNT,
                ICONS.LOCKACCOUNT,
                ICONS.ADD,
                ICONS.ARROWBACK,
                ICONS.ARROWBACKIOS,
                ICONS.CREATEICON,
                ICONS.DELETE,
                ICONS.ATOM,
                ICONS.ARROWFORWARD,
                ICONS.ARROWFORWARDIOS,
                ICONS.ERROR,
                ICONS.ERROROUTLINE,
                ICONS.BELLHORNICON,
                ICONS.INVENTORY,
                ICONS.INVENTORYOUTLINE,
                ICONS.NOTIFICATIONOUTLINE,
                ICONS.REPORTGMAILERROR,
                ICONS.WARNINGAMBER,
                ICONS.INVENTORY,
                ICONS.INVENTORYOUTLINE,
                ICONS.INVITATION,
                ICONS.CANCELICON,
                ICONS.CHECK,
                ICONS.CHECKOUTLINE,
                ICONS.CHECKCIRCLE,
                ICONS.DOUBLEARROWLEFT,
                ICONS.DOUBLEARROWRIGHT,
                ICONS.ARROWDOWN,
                ICONS.ARROWTOP,
                ICONS.ARROWLEFT,
                ICONS.ARROWRIGHT,
                ICONS.ARROWUP,
                ICONS.CIRCLE,
                ICONS.CLOCK,
                ICONS.CANCEL,
                ICONS.CANCELOUTLINE,
                ICONS.SETTINGSICON,
                ICONS.CREDITCARD,
                ICONS.DOTSHORIZOUTLINE,
                ICONS.DOTSVERTLINE,
                ICONS.DOWNLOADICON,
                ICONS.EMOCONFUSED,
                ICONS.EMOCRY,
                ICONS.EMOEXCITED,
                ICONS.EMOSATISFIED,
                ICONS.EMONEUTRAL,
                ICONS.VISIBILITY,
                ICONS.FILTEROUTLINE,
                ICONS.FINANCEOUTLINE,
                ICONS.GIFTCARD,
                ICONS.HANDSHAKE,
                ICONS.HELPCERCLE,
                ICONS.INFOOUTLINE,
                ICONS.SEARCHIOCN,
                ICONS.MENUOUTLINE,
                ICONS.REMOVEICON,
                ICONS.SHIELDACCOUNT,
                ICONS.STARICON,
                ICONS.STARICONPLUS,
                ICONS.TEXTBOXEDIT,
                ICONS.THUMBDOWN,
                ICONS.THUMBUP,
                ICONS.TRASHICON,
                ICONS.UNFOLDMORE,
                ICONS.UPLOADICON,
                ICONS.WINDOWCLOSE,
                ICONS.RELOADICON,
                ICONS.UNFOLDLESSICON
            ],
            control: {type: 'select'}
        },
        submitBtnHasRightIcon: {
            options: [true, false],
            control: {type: "radio"}
        },
        submitBtnRightIcon: {
            options: [
                ICONS.GROUPOUTLINE,
                ICONS.ADDACCOUNT,
                ICONS.LOCKACCOUNT,
                ICONS.ADD,
                ICONS.ARROWBACK,
                ICONS.ARROWBACKIOS,
                ICONS.CREATEICON,
                ICONS.DELETE,
                ICONS.ATOM,
                ICONS.ARROWFORWARD,
                ICONS.ARROWFORWARDIOS,
                ICONS.ERROR,
                ICONS.ERROROUTLINE,
                ICONS.BELLHORNICON,
                ICONS.INVENTORY,
                ICONS.INVENTORYOUTLINE,
                ICONS.NOTIFICATIONOUTLINE,
                ICONS.REPORTGMAILERROR,
                ICONS.WARNINGAMBER,
                ICONS.INVENTORY,
                ICONS.INVENTORYOUTLINE,
                ICONS.INVITATION,
                ICONS.CANCELICON,
                ICONS.CHECK,
                ICONS.CHECKOUTLINE,
                ICONS.CHECKCIRCLE,
                ICONS.DOUBLEARROWLEFT,
                ICONS.DOUBLEARROWRIGHT,
                ICONS.ARROWDOWN,
                ICONS.ARROWTOP,
                ICONS.ARROWLEFT,
                ICONS.ARROWRIGHT,
                ICONS.ARROWUP,
                ICONS.CIRCLE,
                ICONS.CLOCK,
                ICONS.CANCEL,
                ICONS.CANCELOUTLINE,
                ICONS.SETTINGSICON,
                ICONS.CREDITCARD,
                ICONS.DOTSHORIZOUTLINE,
                ICONS.DOTSVERTLINE,
                ICONS.DOWNLOADICON,
                ICONS.EMOCONFUSED,
                ICONS.EMOCRY,
                ICONS.EMOEXCITED,
                ICONS.EMOSATISFIED,
                ICONS.EMONEUTRAL,
                ICONS.VISIBILITY,
                ICONS.FILTEROUTLINE,
                ICONS.FINANCEOUTLINE,
                ICONS.GIFTCARD,
                ICONS.HANDSHAKE,
                ICONS.HELPCERCLE,
                ICONS.INFOOUTLINE,
                ICONS.SEARCHIOCN,
                ICONS.MENUOUTLINE,
                ICONS.REMOVEICON,
                ICONS.SHIELDACCOUNT,
                ICONS.STARICON,
                ICONS.STARICONPLUS,
                ICONS.TEXTBOXEDIT,
                ICONS.THUMBDOWN,
                ICONS.THUMBUP,
                ICONS.TRASHICON,
                ICONS.UNFOLDMORE,
                ICONS.UPLOADICON,
                ICONS.WINDOWCLOSE,
                ICONS.RELOADICON,
                ICONS.UNFOLDLESSICON
            ],
            control: {type: 'select'}
        },
        cancelBtnVariant: {
            options: [MODALVARIANT.PRIMARY, MODALVARIANT.SECONDARY, MODALVARIANT.TERTIARY, MODALVARIANT.TEXT],
            control: {type: 'radio'},
        },
        cancelBtnSize: {
            options: ['default', 'small'],
            control: {type: 'radio'}
        },
        cancelBtnColor: {
            options: [ModalButtonColor.PRIMARY, ModalButtonColor.SECONDARY],
            control: {type: 'radio'}
        },
        cancelBtnHasLeftIcon: {
            options: [true, false],
            control: {type: "radio"}
        },
        cancelBtnLeftIcon: {
            options: [
                ICONS.GROUPOUTLINE,
                ICONS.ADDACCOUNT,
                ICONS.LOCKACCOUNT,
                ICONS.ADD,
                ICONS.ARROWBACK,
                ICONS.ARROWBACKIOS,
                ICONS.CREATEICON,
                ICONS.DELETE,
                ICONS.ATOM,
                ICONS.ARROWFORWARD,
                ICONS.ARROWFORWARDIOS,
                ICONS.ERROR,
                ICONS.ERROROUTLINE,
                ICONS.BELLHORNICON,
                ICONS.INVENTORY,
                ICONS.INVENTORYOUTLINE,
                ICONS.NOTIFICATIONOUTLINE,
                ICONS.REPORTGMAILERROR,
                ICONS.WARNINGAMBER,
                ICONS.INVENTORY,
                ICONS.INVENTORYOUTLINE,
                ICONS.INVITATION,
                ICONS.CANCELICON,
                ICONS.CHECK,
                ICONS.CHECKOUTLINE,
                ICONS.CHECKCIRCLE,
                ICONS.DOUBLEARROWLEFT,
                ICONS.DOUBLEARROWRIGHT,
                ICONS.ARROWDOWN,
                ICONS.ARROWTOP,
                ICONS.ARROWLEFT,
                ICONS.ARROWRIGHT,
                ICONS.ARROWUP,
                ICONS.CIRCLE,
                ICONS.CLOCK,
                ICONS.CANCEL,
                ICONS.CANCELOUTLINE,
                ICONS.SETTINGSICON,
                ICONS.CREDITCARD,
                ICONS.DOTSHORIZOUTLINE,
                ICONS.DOTSVERTLINE,
                ICONS.DOWNLOADICON,
                ICONS.EMOCONFUSED,
                ICONS.EMOCRY,
                ICONS.EMOEXCITED,
                ICONS.EMOSATISFIED,
                ICONS.EMONEUTRAL,
                ICONS.VISIBILITY,
                ICONS.FILTEROUTLINE,
                ICONS.FINANCEOUTLINE,
                ICONS.GIFTCARD,
                ICONS.HANDSHAKE,
                ICONS.HELPCERCLE,
                ICONS.INFOOUTLINE,
                ICONS.SEARCHIOCN,
                ICONS.MENUOUTLINE,
                ICONS.REMOVEICON,
                ICONS.SHIELDACCOUNT,
                ICONS.STARICON,
                ICONS.STARICONPLUS,
                ICONS.TEXTBOXEDIT,
                ICONS.THUMBDOWN,
                ICONS.THUMBUP,
                ICONS.TRASHICON,
                ICONS.UNFOLDMORE,
                ICONS.UPLOADICON,
                ICONS.WINDOWCLOSE,
                ICONS.RELOADICON,
                ICONS.UNFOLDLESSICON
            ],
            control: {type: 'select'}
        },
        cancelBtnHasRightIcon: {
            options: [true, false],
            control: {type: "radio"}
        },
        cancelBtnRightIcon: {
            options: [
                ICONS.GROUPOUTLINE,
                ICONS.ADDACCOUNT,
                ICONS.LOCKACCOUNT,
                ICONS.ADD,
                ICONS.ARROWBACK,
                ICONS.ARROWBACKIOS,
                ICONS.CREATEICON,
                ICONS.DELETE,
                ICONS.ATOM,
                ICONS.ARROWFORWARD,
                ICONS.ARROWFORWARDIOS,
                ICONS.ERROR,
                ICONS.ERROROUTLINE,
                ICONS.BELLHORNICON,
                ICONS.INVENTORY,
                ICONS.INVENTORYOUTLINE,
                ICONS.NOTIFICATIONOUTLINE,
                ICONS.REPORTGMAILERROR,
                ICONS.WARNINGAMBER,
                ICONS.INVENTORY,
                ICONS.INVENTORYOUTLINE,
                ICONS.INVITATION,
                ICONS.CANCELICON,
                ICONS.CHECK,
                ICONS.CHECKOUTLINE,
                ICONS.CHECKCIRCLE,
                ICONS.DOUBLEARROWLEFT,
                ICONS.DOUBLEARROWRIGHT,
                ICONS.ARROWDOWN,
                ICONS.ARROWTOP,
                ICONS.ARROWLEFT,
                ICONS.ARROWRIGHT,
                ICONS.ARROWUP,
                ICONS.CIRCLE,
                ICONS.CLOCK,
                ICONS.CANCEL,
                ICONS.CANCELOUTLINE,
                ICONS.SETTINGSICON,
                ICONS.CREDITCARD,
                ICONS.DOTSHORIZOUTLINE,
                ICONS.DOTSVERTLINE,
                ICONS.DOWNLOADICON,
                ICONS.EMOCONFUSED,
                ICONS.EMOCRY,
                ICONS.EMOEXCITED,
                ICONS.EMOSATISFIED,
                ICONS.EMONEUTRAL,
                ICONS.VISIBILITY,
                ICONS.FILTEROUTLINE,
                ICONS.FINANCEOUTLINE,
                ICONS.GIFTCARD,
                ICONS.HANDSHAKE,
                ICONS.HELPCERCLE,
                ICONS.INFOOUTLINE,
                ICONS.SEARCHIOCN,
                ICONS.MENUOUTLINE,
                ICONS.REMOVEICON,
                ICONS.SHIELDACCOUNT,
                ICONS.STARICON,
                ICONS.STARICONPLUS,
                ICONS.TEXTBOXEDIT,
                ICONS.THUMBDOWN,
                ICONS.THUMBUP,
                ICONS.TRASHICON,
                ICONS.UNFOLDMORE,
                ICONS.UPLOADICON,
                ICONS.WINDOWCLOSE,
                ICONS.RELOADICON,
                ICONS.UNFOLDLESSICON
            ],
            control: {type: 'select'}
        }
    }
}